/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceSupportRouteImport } from './routes/_workspace.support'
import { Route as WorkspaceSprintsRouteImport } from './routes/_workspace.sprints'
import { Route as WorkspaceSettingsRouteImport } from './routes/_workspace.settings'
import { Route as WorkspaceDashboardRouteImport } from './routes/_workspace.dashboard'
import { Route as WorkspaceBoardsRouteImport } from './routes/_workspace.boards'
import { Route as WorkspaceBacklogRouteImport } from './routes/_workspace.backlog'
import { Route as WorkspaceAutomationRouteImport } from './routes/_workspace.automation'
import { Route as WorkspaceSettingsIndexRouteImport } from './routes/_workspace.settings.index'
import { Route as WorkspaceProjectsIndexRouteImport } from './routes/_workspace.projects.index'
import { Route as WorkspaceWorkItemsItemIdRouteImport } from './routes/_workspace.work-items.$itemId'
import { Route as WorkspaceSettingsMembersRouteImport } from './routes/_workspace.settings.members'
import { Route as WorkspaceProjectsProjectIdRouteImport } from './routes/_workspace.projects.$projectId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSupportRoute = WorkspaceSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSprintsRoute = WorkspaceSprintsRouteImport.update({
  id: '/sprints',
  path: '/sprints',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDashboardRoute = WorkspaceDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceBoardsRoute = WorkspaceBoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceBacklogRoute = WorkspaceBacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAutomationRoute = WorkspaceAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsIndexRoute = WorkspaceSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceSettingsRoute,
} as any)
const WorkspaceProjectsIndexRoute = WorkspaceProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceWorkItemsItemIdRoute =
  WorkspaceWorkItemsItemIdRouteImport.update({
    id: '/work-items/$itemId',
    path: '/work-items/$itemId',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceSettingsMembersRoute =
  WorkspaceSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => WorkspaceSettingsRoute,
  } as any)
const WorkspaceProjectsProjectIdRoute =
  WorkspaceProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => WorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/automation': typeof WorkspaceAutomationRoute
  '/backlog': typeof WorkspaceBacklogRoute
  '/boards': typeof WorkspaceBoardsRoute
  '/dashboard': typeof WorkspaceDashboardRoute
  '/settings': typeof WorkspaceSettingsRouteWithChildren
  '/sprints': typeof WorkspaceSprintsRoute
  '/support': typeof WorkspaceSupportRoute
  '/projects/$projectId': typeof WorkspaceProjectsProjectIdRoute
  '/settings/members': typeof WorkspaceSettingsMembersRoute
  '/work-items/$itemId': typeof WorkspaceWorkItemsItemIdRoute
  '/projects/': typeof WorkspaceProjectsIndexRoute
  '/settings/': typeof WorkspaceSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/automation': typeof WorkspaceAutomationRoute
  '/backlog': typeof WorkspaceBacklogRoute
  '/boards': typeof WorkspaceBoardsRoute
  '/dashboard': typeof WorkspaceDashboardRoute
  '/sprints': typeof WorkspaceSprintsRoute
  '/support': typeof WorkspaceSupportRoute
  '/projects/$projectId': typeof WorkspaceProjectsProjectIdRoute
  '/settings/members': typeof WorkspaceSettingsMembersRoute
  '/work-items/$itemId': typeof WorkspaceWorkItemsItemIdRoute
  '/projects': typeof WorkspaceProjectsIndexRoute
  '/settings': typeof WorkspaceSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_workspace/automation': typeof WorkspaceAutomationRoute
  '/_workspace/backlog': typeof WorkspaceBacklogRoute
  '/_workspace/boards': typeof WorkspaceBoardsRoute
  '/_workspace/dashboard': typeof WorkspaceDashboardRoute
  '/_workspace/settings': typeof WorkspaceSettingsRouteWithChildren
  '/_workspace/sprints': typeof WorkspaceSprintsRoute
  '/_workspace/support': typeof WorkspaceSupportRoute
  '/_workspace/projects/$projectId': typeof WorkspaceProjectsProjectIdRoute
  '/_workspace/settings/members': typeof WorkspaceSettingsMembersRoute
  '/_workspace/work-items/$itemId': typeof WorkspaceWorkItemsItemIdRoute
  '/_workspace/projects/': typeof WorkspaceProjectsIndexRoute
  '/_workspace/settings/': typeof WorkspaceSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/automation'
    | '/backlog'
    | '/boards'
    | '/dashboard'
    | '/settings'
    | '/sprints'
    | '/support'
    | '/projects/$projectId'
    | '/settings/members'
    | '/work-items/$itemId'
    | '/projects/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/automation'
    | '/backlog'
    | '/boards'
    | '/dashboard'
    | '/sprints'
    | '/support'
    | '/projects/$projectId'
    | '/settings/members'
    | '/work-items/$itemId'
    | '/projects'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/login'
    | '/unauthorized'
    | '/_workspace/automation'
    | '/_workspace/backlog'
    | '/_workspace/boards'
    | '/_workspace/dashboard'
    | '/_workspace/settings'
    | '/_workspace/sprints'
    | '/_workspace/support'
    | '/_workspace/projects/$projectId'
    | '/_workspace/settings/members'
    | '/_workspace/work-items/$itemId'
    | '/_workspace/projects/'
    | '/_workspace/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/support': {
      id: '/_workspace/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof WorkspaceSupportRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/sprints': {
      id: '/_workspace/sprints'
      path: '/sprints'
      fullPath: '/sprints'
      preLoaderRoute: typeof WorkspaceSprintsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/dashboard': {
      id: '/_workspace/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof WorkspaceDashboardRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/boards': {
      id: '/_workspace/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof WorkspaceBoardsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/backlog': {
      id: '/_workspace/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof WorkspaceBacklogRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/automation': {
      id: '/_workspace/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof WorkspaceAutomationRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/settings/': {
      id: '/_workspace/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof WorkspaceSettingsIndexRouteImport
      parentRoute: typeof WorkspaceSettingsRoute
    }
    '/_workspace/projects/': {
      id: '/_workspace/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof WorkspaceProjectsIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/work-items/$itemId': {
      id: '/_workspace/work-items/$itemId'
      path: '/work-items/$itemId'
      fullPath: '/work-items/$itemId'
      preLoaderRoute: typeof WorkspaceWorkItemsItemIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/settings/members': {
      id: '/_workspace/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof WorkspaceSettingsMembersRouteImport
      parentRoute: typeof WorkspaceSettingsRoute
    }
    '/_workspace/projects/$projectId': {
      id: '/_workspace/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof WorkspaceProjectsProjectIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceSettingsRouteChildren {
  WorkspaceSettingsMembersRoute: typeof WorkspaceSettingsMembersRoute
  WorkspaceSettingsIndexRoute: typeof WorkspaceSettingsIndexRoute
}

const WorkspaceSettingsRouteChildren: WorkspaceSettingsRouteChildren = {
  WorkspaceSettingsMembersRoute: WorkspaceSettingsMembersRoute,
  WorkspaceSettingsIndexRoute: WorkspaceSettingsIndexRoute,
}

const WorkspaceSettingsRouteWithChildren =
  WorkspaceSettingsRoute._addFileChildren(WorkspaceSettingsRouteChildren)

interface WorkspaceRouteChildren {
  WorkspaceAutomationRoute: typeof WorkspaceAutomationRoute
  WorkspaceBacklogRoute: typeof WorkspaceBacklogRoute
  WorkspaceBoardsRoute: typeof WorkspaceBoardsRoute
  WorkspaceDashboardRoute: typeof WorkspaceDashboardRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRouteWithChildren
  WorkspaceSprintsRoute: typeof WorkspaceSprintsRoute
  WorkspaceSupportRoute: typeof WorkspaceSupportRoute
  WorkspaceProjectsProjectIdRoute: typeof WorkspaceProjectsProjectIdRoute
  WorkspaceWorkItemsItemIdRoute: typeof WorkspaceWorkItemsItemIdRoute
  WorkspaceProjectsIndexRoute: typeof WorkspaceProjectsIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceAutomationRoute: WorkspaceAutomationRoute,
  WorkspaceBacklogRoute: WorkspaceBacklogRoute,
  WorkspaceBoardsRoute: WorkspaceBoardsRoute,
  WorkspaceDashboardRoute: WorkspaceDashboardRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRouteWithChildren,
  WorkspaceSprintsRoute: WorkspaceSprintsRoute,
  WorkspaceSupportRoute: WorkspaceSupportRoute,
  WorkspaceProjectsProjectIdRoute: WorkspaceProjectsProjectIdRoute,
  WorkspaceWorkItemsItemIdRoute: WorkspaceWorkItemsItemIdRoute,
  WorkspaceProjectsIndexRoute: WorkspaceProjectsIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
